version: '3.8'

networks:
  shared-network:
    driver: bridge

volumes:
  database-data:

services:

  db:
    container_name: marvel_db
    networks:
      - shared-network
    image: postgres:13
    ports:
    - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./business/data/schema/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=marvel

  caching:
    container_name: marvel_caching
    networks:
      - shared-network
    image: redis
    ports:
    - 6379:6379

  marvel:
    container_name: marvel
    networks:
      - shared-network
    image: marvel:latest
    ports:
      - 8080:8080
    depends_on:
      - db